language: c
dist: trusty
sudo: true

script:
  - sudo apt-get -y install expect csh zsh
  - ( cd firejail ; ./configure --prefix=/usr --enable-git-install && make && sudo make install && make test-travis )
